### PR TITLE
Support for TD Problems [WIP]

### PR DESCRIPTION
**Pull request by eldarkh**
This is a WIP dirty first draft of time dependent problem and its dependencies. There is plenty of aspects that need to be taken care of and modified, so I think it would be good to have a PR open to have a way to discuss everything. 

At the moment this is rather featureless, although working, implementation of Backward Euler time dependent problem satisfying the API requirements of `Model` class and all the underlying methods within `hippylib` (except for one place in MCMC, that is also being taken care of atm).

Things that I am working on right now include:
1. Support for various explicit and implicit time discretization schemes - for this I follow the design used in deal.ii (see [docs](https://github.com/dealii/dealii/blob/master/include/deal.II/base/time_stepping.h) or [tutorial](https://www.dealii.org/8.4.0/doxygen/deal.II/step_52.html) for example). This design looks quite clean and easy to use for the users. I did make some progress on this already, so it will not take long to finalize this.
2. I will add a way to modify the solution after each time step - like clipping the solution to [0,1] bounds for concentration for instance - this will be done by allowing TDProblem to have user provided callback functions.
3. I have not verified that all Update LHS/RHS flags and their logic are working correctly - will do it shortly and clean them up overall.

I would be happy to hear what you think of (1) , since it is quite a fundamental decision for the design of the entire class. Also, any other suggestions about the above are much appreciated.

Previous comments from Umberto that I have not addressed in any way so far:
1. Allowing the class to work in different inverse problems settings - invert for IC, for parameters or for the source. At the moment I had inversion for parameters in mind only.
2. Time-dependent parameters and whole story of space/time priors
3. "Continuous in time" misfit

### CODE REVIEW

**Comment by uvilla** [comment]
Hi @eldarkh ,

Thank you very much for getting this PR started :)
I have not looked into it in details, but it seems a very good start!

- I am not familiar with deal.II, but I know it is a very well-thought library. It is definitely a good idea to learn how they handle different time integrators, and see how we can apply the same logic in hIPPYlib

- One important comment is about the naming convention. In hippylib 1.x, we called the sought-after parameter `a`, but we rename it to `m` as in hippylib 2.0.0.
This was mainly due to be consistent with the *A Computational Framework for Infinite-Dimensional Bayesian Inverse Problems*  papers.

- In the computation of second order derivatives in `TimeDependentPDEVariationalProblem` there is a bit of waste of computations.
For example, in `applyC` you first assemble the operator C as a matrix, then you apply b.c., and finally you multiply the matrix `C` by the vector `dm` (`da` in your code).
A more efficient way to do this is to directly compute the action of `C` in the direction `dm` at the variational form level, and then assemble the vector.
Something like:
```
test = dl.TestFunction(self.Vh[STATE])
dm_fun = vector2Function(dm, self.Vh[PARAMETER])
Cdm_varf = dl.lhs(dl.derivative(dl.derivative(varf, p, test), m, dm_fun)) )
Cdm = dl.assemble(Cdm_varf)
[bc.apply(Cdm) for bc in self.adj_bc]
```

**Comment by uvilla** [comment]
It may be also worth to see how Adrian Sandu designed his [FatODE](http://people.cs.vt.edu/~asandu/Software/FATODE/index.html) software

**Comment by eldarkh** [comment]
@uvilla Thanks for the comments, I will work on these over the weekend. I will also take a look at how folks from FatODE do the time stepping in case we can benefit from it.

**Comment by eldarkh** [comment]
I just realized that I am reinventing the wheel with time stepping here, fenics provides various method ([here](https://fenicsproject.org/docs/dolfin/2017.2.0/python/search.html?q=multistage&check_keywords=yes&area=default)) - I will try to figure out how one can use them as documentation is sparse.

**Comment by uvilla** [comment]
@eldarkh ,

You are right that FEniCS already has some type of time integrators, but I never  looked into then nor I'm sure if they are fully supported/maintained.

Probably a start could be this test in dolfin:
https://bitbucket.org/fenics-project/dolfin/src/2017.2.0.post0/test/unit/python/multistage/test_RK_solver.py
or the undocumented demo:
https://bitbucket.org/fenics-project/dolfin/src/2017.2.0.post0/demo/undocumented/multistage-solver/python/demo_multistage-solver.py

It may be worth to reach out to the Fenics community either [here](https://www.allanswered.com/community/s/fenics-project/) or on [slack](https://fenicsproject-slack-invite.herokuapp.com/).

**Comment by eldarkh** [comment]
@uvilla Thanks, that's exactly what I have found - the link I have posted leads to the github version of the same demo :)

**Comment by minakari** [comment]
@eldarkh @uvilla 
Hi,

I want to solve the advection-diffusion example with kappa (permeability) as a controlling parameter (not initial condition).So, the C block for me is different from the example in advection-diffusion code. 
For this problem the C block is  ( m \nabla u. \nabla p ) instead of (-p0 * m). 
I think I have to change three parts 1. evalGradientParameter 2. applyC and 3.applyCt 
I would be appreciated if you could help me to assemble the operator C.
Should I use N in order to construct C matrix instead of M?

Thanks,

**Comment by uvilla** [comment]
This PR has been superseded by #66.

**Pull request closed without merging**
